In [ ]:
# Steps
#1.Data collection
#2.Data processing
#3.Model training

In [ ]:
# import libraries
import pandas as pd
import numpy as np

In [ ]:
laptops = pd.read_csv("laptops.csv")

In [ ]:
laptops.head(3)

laptop_id                                               name   price  \
0          0                      Lenovo Intel Core i5 11th Gen   62990   
1          1  ASUS ROG Zephyrus G15 (2022) with 90Whr Batter...  161990   
2          2           ASUS VivoBook 15 (2022) Core i3 10th Gen   33990   

                            processor             ram  \
0  Intel Core i5 Processor (11th Gen)  16 GB DDR4 RAM   
1     AMD Ryzen 9 Octa Core Processor  16 GB DDR5 RAM   
2  Intel Core i3 Processor (10th Gen)   8 GB DDR4 RAM   

                                   os     storage  \
0         Windows 11 Operating System  512 GB SSD   
1  64 bit Windows 11 Operating System    1 TB SSD   
2  64 bit Windows 11 Operating System  512 GB SSD   

                                            img_link  display  rating  \
0  https://rukminim1.flixcart.com/image/312/312/x...     15.6     4.5   
1  https://rukminim1.flixcart.com/image/312/312/l...     15.6     3.8   
2  https://rukminim1.flixcart.com/image/312/312/x...     15.6     4.3   

   no_of_ratings  no_of_reviews laptop_brand os_brand processor_brand  \
0           14.0            1.0       Lenovo  Windows           Intel   
1            5.0            1.0         ASUS  Windows             AMD   
2        10406.0         1040.0         ASUS  Windows           Intel   

                 usecases  
0   Business/Professional  
1                  Gaming  
2       Home/Everyday use

In [ ]:
laptops.shape

(796, 16)

In [ ]:
laptops.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 796 entries, 0 to 795
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   laptop_id        796 non-null    int64  
 1   name             796 non-null    object 
 2   price            796 non-null    int64  
 3   processor        796 non-null    object 
 4   ram              796 non-null    object 
 5   os               796 non-null    object 
 6   storage          796 non-null    object 
 7   img_link         796 non-null    object 
 8   display          796 non-null    float64
 9   rating           530 non-null    float64
 10  no_of_ratings    530 non-null    float64
 11  no_of_reviews    530 non-null    float64
 12  laptop_brand     796 non-null    object 
 13  os_brand         796 non-null    object 
 14  processor_brand  796 non-null    object 
 15  usecases         796 non-null    object 
dtypes: float64(4), int64(2), object(10)
memory usage: 99.6+ KB


In [ ]:
laptops = laptops[['laptop_id','img_link','name','price','processor','ram','os','storage','rating','laptop_brand','os_brand','processor_brand','usecases']]

In [ ]:
laptops.head(3)

laptop_id                                           img_link  \
0          0  https://rukminim1.flixcart.com/image/312/312/x...   
1          1  https://rukminim1.flixcart.com/image/312/312/l...   
2          2  https://rukminim1.flixcart.com/image/312/312/x...   

                                                name   price  \
0                      Lenovo Intel Core i5 11th Gen   62990   
1  ASUS ROG Zephyrus G15 (2022) with 90Whr Batter...  161990   
2           ASUS VivoBook 15 (2022) Core i3 10th Gen   33990   

                            processor             ram  \
0  Intel Core i5 Processor (11th Gen)  16 GB DDR4 RAM   
1     AMD Ryzen 9 Octa Core Processor  16 GB DDR5 RAM   
2  Intel Core i3 Processor (10th Gen)   8 GB DDR4 RAM   

                                   os     storage  rating laptop_brand  \
0         Windows 11 Operating System  512 GB SSD     4.5       Lenovo   
1  64 bit Windows 11 Operating System    1 TB SSD     3.8         ASUS   
2  64 bit Windows 11 Operating System  512 GB SSD     4.3         ASUS   

  os_brand processor_brand                usecases  
0  Windows           Intel   Business/Professional  
1  Windows             AMD                  Gaming  
2  Windows           Intel       Home/Everyday use

In [ ]:
# MISSING VALUES

In [ ]:
laptops.isnull().sum()

laptop_id            0
img_link             0
name                 0
price                0
processor            0
ram                  0
os                   0
storage              0
rating             266
laptop_brand         0
os_brand             0
processor_brand      0
usecases             0
dtype: int64

In [ ]:
laptops.dropna(inplace=True)

In [ ]:
laptops.duplicated().sum()

0

In [ ]:
laptops.iloc[0].laptop_brand

'Lenovo'

In [ ]:
laptops.head(1)

laptop_id                                           img_link  \
0          0  https://rukminim1.flixcart.com/image/312/312/x...   

                            name  price                           processor  \
0  Lenovo Intel Core i5 11th Gen  62990  Intel Core i5 Processor (11th Gen)   

              ram                           os     storage  rating  \
0  16 GB DDR4 RAM  Windows 11 Operating System  512 GB SSD     4.5   

  laptop_brand os_brand processor_brand                usecases  
0       Lenovo  Windows           Intel   Business/Professional

Laptop ID

In [ ]:
laptops['processor'] = laptops['processor'].apply(lambda x:x.split())
laptops['ram'] = laptops['ram'].apply(lambda x:x.split())
laptops['os'] = laptops['os'].apply(lambda x:x.split())
laptops['use'] = laptops['usecases'].apply(lambda x:x.split())

In [ ]:
laptops['tags'] = laptops['processor']+laptops['ram']+laptops['os']+laptops['use']

In [ ]:
laptops.head(1)

laptop_id                                           img_link  \
0          0  https://rukminim1.flixcart.com/image/312/312/x...   

                            name  price  \
0  Lenovo Intel Core i5 11th Gen  62990   

                                   processor                  ram  \
0  [Intel, Core, i5, Processor, (11th, Gen)]  [16, GB, DDR4, RAM]   

                                 os     storage  rating laptop_brand os_brand  \
0  [Windows, 11, Operating, System]  512 GB SSD     4.5       Lenovo  Windows   

  processor_brand                usecases                      use  \
0           Intel   Business/Professional  [Business/Professional]   

                                                tags  
0  [Intel, Core, i5, Processor, (11th, Gen), 16, ...

In [ ]:
laptops.iloc[0].tags

['Intel',
 'Core',
 'i5',
 'Processor',
 '(11th',
 'Gen)',
 '16',
 'GB',
 'DDR4',
 'RAM',
 'Windows',
 '11',
 'Operating',
 'System',
 'Business/Professional']

In [ ]:
new = laptops.drop(columns=['processor','ram','os','storage','rating','os_brand','processor_brand','use'])

In [ ]:
new.head(2)

laptop_id                                           img_link  \
0          0  https://rukminim1.flixcart.com/image/312/312/x...   
1          1  https://rukminim1.flixcart.com/image/312/312/l...   

                                                name   price laptop_brand  \
0                      Lenovo Intel Core i5 11th Gen   62990       Lenovo   
1  ASUS ROG Zephyrus G15 (2022) with 90Whr Batter...  161990         ASUS   

                 usecases                                               tags  
0   Business/Professional  [Intel, Core, i5, Processor, (11th, Gen), 16, ...  
1                  Gaming  [AMD, Ryzen, 9, Octa, Core, Processor, 16, GB,...

In [ ]:
new['tags'] = new['tags'].apply(lambda x:" ".join(x))

In [ ]:
new.iloc[0].tags

'Intel Core i5 Processor (11th Gen) 16 GB DDR4 RAM Windows 11 Operating System Business/Professional'

In [ ]:
new['tags'] = new['tags'].apply(lambda x:x.lower())

In [ ]:
new.head(2)

laptop_id                                           img_link  \
0          0  https://rukminim1.flixcart.com/image/312/312/x...   
1          1  https://rukminim1.flixcart.com/image/312/312/l...   

                                                name   price laptop_brand  \
0                      Lenovo Intel Core i5 11th Gen   62990       Lenovo   
1  ASUS ROG Zephyrus G15 (2022) with 90Whr Batter...  161990         ASUS   

                 usecases                                               tags  
0   Business/Professional  intel core i5 processor (11th gen) 16 gb ddr4 ...  
1                  Gaming  amd ryzen 9 octa core processor 16 gb ddr5 ram...

In [ ]:
new.iloc[0].tags

'intel core i5 processor (11th gen) 16 gb ddr4 ram windows 11 operating system business/professional'

In [ ]:
import nltk

In [ ]:
from nltk.stem.porter import PorterStemmer

In [ ]:
ps = PorterStemmer()

In [ ]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

In [ ]:
new['tags'] = new['tags'].apply(stem)

In [ ]:
new.head(2)

laptop_id                                           img_link  \
0          0  https://rukminim1.flixcart.com/image/312/312/x...   
1          1  https://rukminim1.flixcart.com/image/312/312/l...   

                                                name   price laptop_brand  \
0                      Lenovo Intel Core i5 11th Gen   62990       Lenovo   
1  ASUS ROG Zephyrus G15 (2022) with 90Whr Batter...  161990         ASUS   

                 usecases                                               tags  
0   Business/Professional  intel core i5 processor (11th gen) 16 gb ddr4 ...  
1                  Gaming  amd ryzen 9 octa core processor 16 gb ddr5 ram...

In [ ]:
# counter vectorizing

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv = CountVectorizer(max_features = 5000, stop_words='english')

In [ ]:
vector = cv.fit_transform(new['tags']).toarray()

In [ ]:
vector

array([[0, 0, 1, ..., 0, 0, 1],
       [0, 0, 1, ..., 0, 0, 1],
       [0, 1, 1, ..., 0, 1, 1],
       ...,
       [0, 0, 1, ..., 0, 0, 1],
       [0, 0, 1, ..., 0, 0, 1],
       [0, 0, 1, ..., 0, 0, 1]])

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
similarity = cosine_similarity(vector)

In [ ]:
similarity

array([[1.        , 0.53333333, 0.62622429, ..., 0.6       , 0.59628479,
        0.83914639],
       [0.53333333, 1.        , 0.56360186, ..., 0.6       , 0.74535599,
        0.5809475 ],
       [0.62622429, 0.56360186, 1.        , ..., 0.68884672, 0.56011203,
        0.78824078],
       ...,
       [0.6       , 0.6       , 0.68884672, ..., 1.        , 0.59628479,
        0.71004695],
       [0.59628479, 0.74535599, 0.56011203, ..., 0.59628479, 1.        ,
        0.57735027],
       [0.83914639, 0.5809475 , 0.78824078, ..., 0.71004695, 0.57735027,
        1.        ]])

In [ ]:
similarity[0]

array([1.        , 0.53333333, 0.62622429, 0.46709937, 0.38924947,
       0.6       , 0.68884672, 0.96609178, 0.51639778, 0.87671401,
       0.83914639, 0.93333333, 0.89708523, 0.62622429, 0.68884672,
       0.71004695, 0.66666667, 0.68884672, 0.38924947, 0.62622429,
       0.90369611, 0.66666667, 0.68884672, 0.82807867, 0.53333333,
       0.83914639, 0.66666667, 0.53333333, 0.83914639, 1.        ,
       0.53333333, 0.5809475 , 0.83914639, 0.83914639, 0.50128041,
       0.66666667, 0.77459667, 0.90369611, 0.62622429, 0.64549722,
       0.87671401, 0.83914639, 0.55205245, 0.68884672, 0.53333333,
       0.87671401, 0.68884672, 0.90369611, 0.6       , 0.55205245,
       0.77459667, 0.89708523, 0.55205245, 0.38924947, 0.93933644,
       0.55205245, 0.82807867, 0.83914639, 0.4472136 , 0.4472136 ,
       0.77459667, 0.5809475 , 0.71004695, 0.48304589, 0.87671401,
       0.53333333, 0.51639778, 0.77459667, 0.83914639, 0.83914639,
       0.71611487, 0.96609178, 0.51639778, 0.83914639, 0.77459

In [ ]:
len(similarity[0])

530

In [ ]:
#Recommend

In [ ]:
def recommend(laptop):
    index = new[new['usecases']==laptop].index[0]
    distances = sorted(list(enumerate(similarity[index])), reverse=True, key = lambda x:x[1])
    for i in distances[1:10]:
        print(new.iloc[i[0]].usecases)

In [ ]:
def recommend(use):
    index = new[new['usecases'] == use].index[0]
    distances = sorted(list(enumerate(similarity[index])), reverse=True, key=lambda x: x[1])
    printed_names = set()
    for i in distances[1:50]:
        row_index = i[0]
        name = new.iloc[row_index]['name']
        if name not in printed_names:
            printed_names.add(name)
            print(name)

In [ ]:
sorted(list(enumerate(similarity[0])), reverse=True, key = lambda x:x[1])

[(0, 0.9999999999999998),
 (29, 0.9999999999999998),
 (470, 0.9999999999999998),
 (7, 0.966091783079296),
 (71, 0.966091783079296),
 (120, 0.966091783079296),
 (439, 0.966091783079296),
 (54, 0.9393364366277238),
 (90, 0.9393364366277238),
 (196, 0.9393364366277238),
 (480, 0.9393364366277238),
 (11, 0.9333333333333331),
 (261, 0.9333333333333331),
 (303, 0.9333333333333331),
 (20, 0.9036961141150636),
 (37, 0.9036961141150636),
 (47, 0.9036961141150636),
 (91, 0.9036961141150636),
 (136, 0.9036961141150636),
 (486, 0.9036961141150636),
 (519, 0.9036961141150636),
 (12, 0.8970852271450606),
 (51, 0.8970852271450606),
 (99, 0.8970852271450606),
 (362, 0.8970852271450606),
 (9, 0.8767140075192089),
 (40, 0.8767140075192089),
 (45, 0.8767140075192089),
 (64, 0.8767140075192089),
 (76, 0.8767140075192089),
 (80, 0.8767140075192089),
 (92, 0.8767140075192089),
 (96, 0.8767140075192089),
 (98, 0.8767140075192089),
 (108, 0.8767140075192089),
 (469, 0.8767140075192089),
 (84, 0.86666666666666

In [ ]:
"""
 Gaming
 Business/Professional
 Multimedia/Entertainment
 Student/Education
 Creative/Design
 Travel/On-the-go
 Home/Everyday use
 Programming/Development
 Budget-Friendly
 Ultra-portable
"""

'\n Gaming\n Business/Professional\n Multimedia/Entertainment\n Student/Education\n Creative/Design\n Travel/On-the-go\n Home/Everyday use\n Programming/Development\n Budget-Friendly\n Ultra-portable\n'

In [ ]:
recommend(" Budget Friendly")

HP Athlon Dual Core 3050U
HP G8 Ryzen 3 Dual Core AMD Ryzen 3 3250U
HP Ryzen 3 Dual Core
Lenovo Athlon Dual Core 3050U
DELL Inspiron Ryzen 3 Dual Core 3250U
acer Aspire 3 Ryzen 3 Dual Core R33250U
HP Ryzen 3 Dual Core 3250U
Avita PURA APU Dual Core A6 9220e
Lenovo Ideapad AMD Ryzen 5 Hexa Core 5500U
Lenovo Celeron Dual Core
ASUS VivoBook 14 (2021) Celeron Dual Core
DELL Ryzen 5 Quad Core 3450U
Lenovo IdeaPad 1 Ryzen 5 Quad Core 3500U
DELL Ryzen 3 Quad Core 5425U
Avita SATUS S111 Celeron Dual Core
Lenovo IdeaPad 3 Ryzen 5 Hexa Core 5500U
acer Aspire 3 Celeron Dual Core
ASUS (2022) Celeron Dual Core
HP Pavilion Ryzen 5 Hexa Core AMD R5
ASUS Chromebook Celeron Dual Core
ASUS Chromebook Flip Touch Celeron Dual Core
HP 250 G8 Core i3 11th Gen
Lenovo IdeaPad 3 Chromebook Celeron Dual Core
ASUS Vivobook 15 Ryzen 3 Dual Core AMD R3
ASUS EeeBook 12 Celeron Dual Core 4th Gen
Lenovo Core i3 10th Gen
HP Core i3 11th Gen
RedmiBook 15 Core i3 11th Gen
Lenovo IdeaPad 3 Dual Core 3020e
ASUS Core i5 10

In [ ]:
1120